---
- name: Se till att senaste versionen av MariaDB-paketet är installerat.
  yum:
    name: "{{ item }}"
    state: latest
  loop:   
    - mariadb-server
    - MySQL-python

- name: Starta MariaDB vid boot.
  service:
    name: mariadb
    enabled: yes
    state: started

- name: kopiera sql filen til dbserver
  copy:
    src: files/webappdb.sql
    dest: /tmp/webappdb.sql
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Skapa användaren webappuser samt ge pw
  mysql_user:
    name: "{{ webapp_db_user }}" 
    host: "{{ webapp_db_connection_for_webappusers }}"
    password: "{{ webapp_db_password }}"
    priv: "*.*:ALL"
    state: present

- name: skapa databas tabeller med hjälp av sql filen
  mysql_db:
    name: "{{ webapp_db_dbname }}"
    state: import
    target: /tmp/webappdb.sql

